### ISSUE TITLE
A few small things

### ISSUE THREAD

**Issue by b-t-k** [johnrambow/william-dean-howells_a-hazard-of-new-fortunes#1]
## typogrify
- there are a couple of typogrify changes I think you should make

## modernize spelling
Nonexistant, shanty-town

## Chapter 1-11 
-line 58 Add xml:lang to *L’Etrangère*

## Chapter 1-8
- line 23 Add xml:lang to arrière-pensée ??? Not sure abut this one but so many other simple french phrases have been marked i.e. _merci_, it makes me wonder if you should at least add a <span xml:lang="fr"> to it. But I will leave it up to you superior knowledge of the text.

## content.opf
This short dec seems a bit awkward. Maybe add a "both" before "in the struggles"? Again discretionary as Alex usually fusses with these anyway.
<dc:description id="description">A Boston-based editor moves his family to Gilded Age New York, where they are soon caught up in the struggles of the time and those around them.</dc:description>

**Comment by johnrambow** [comment]
Thanks, these should all be fixed now. And I modernized a couple other phrases that were bugging me.
